### PR TITLE
fix: rename get_workspace_sidebar_items to get_workspaces

### PR DESCRIPTION
**Pull request by mn3m-cs**
## Problem

Installing Solvronix Desk on Frappe v16 (v16.27.1) causes a ValidationError:

```
frappe.exceptions.ValidationError: Failed to get method for command frappe.desk.desktop.get_workspace_sidebar_items with module 'frappe.desk.desktop' has no attribute 'get_workspace_sidebar_items'
```

## Cause

Frappe v16 PR [#39835](https://github.com/frappe/frappe/pull/39835) renamed `get_workspace_sidebar_items` to `get_workspaces` in `frappe/desk/desktop.py`.

## Fix

Updated all references from `frappe.desk.desktop.get_workspace_sidebar_items` to `frappe.desk.desktop.get_workspaces` in:

- `solvronix_desk/public/js/solvronix_desk.js` (2 occurrences)
- `solvronix_desk/public/js/module_cards.js` (1 occurrence)

## Testing

Verified the fix works on Frappe v16.27.1 with ERPNext v16.28.0 and HRMS v16.13.0.

### CODE REVIEW

**Comment by ehsanjavaid** [comment]
Hi @mn3m-cs , thanks for the detailed report and PR — appreciate you digging into the root cause.

Confirmed: Frappe renamed get_workspace_sidebar_items → get_workspaces sometime between v16.18 and v16.21 (checked directly against frappe/frappe — the function body is unchanged, it's a pure rename, no alias kept for the old name).

I can't merge the rename as-is though: our own production bench (and likely other users) are still on v16.18, which only has the old name — a hard switch to get_workspaces would fix newer installs but break ours and theirs. Solvronix Desk needs to work across the v16 line, so trading one crash for another isn't a fix.

Instead I've added a small server-side shim in our own api.py that resolves whichever method name exists at runtime, and pointed the 3 JS call sites at it instead of calling the Frappe core method directly. Same response shape, no other changes needed.

I've credited you in the commit/changelog for finding and diagnosing this — really solid first contribution, the version bisection would've taken me longer to track down. Closing this PR in favor of that commit, but happy to have you review it if you want to see the approach.
